---
name: Modern-Perl
version: 1.03
author:
  - 'chromatic <chromatic@wgz.org>'
abstract: enable all of the features of Modern Perl with one command
license: perl
resources:
  license: ~
build_requires:
  Test::Simple: 0.8
  perl: 5.01
provides:
  Modern::Perl:
    file: lib/Modern/Perl.pm
    version: 1.03
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
